/** Reviewed leads, not a list of installed dependencies or guaranteed data feeds. */
export type SourceCategory = "metadata" | "tracking" | "annotation";
export type SourceStatus = "preview" | "candidate" | "research" | "hold";
export type Source = {
  id: string;
  name: string;
  category: SourceCategory;
  status: SourceStatus;
  url: string;
  license: string;
  ar: string;
  en: string;
};
export const reviewedAt = "2026-10-08";
export const sources: readonly Source[] = [
  {
    id: "wikidata",
    name: "Wikidata",
    category: "metadata",
    status: "preview",
    url: "https://www.wikidata.org/wiki/Wikidata:Data_access",
    license: "CC0 — structured data",
    ar: "بحث ومعاينة أسماء لاعبي اليد بالعربية والإنجليزية مع معرّف ثابت ومراجعة المصدر. ليس مصدرًا لقوائم الموسم أو الإحصاءات الحية.",
    en: "Search and preview handball player names in Arabic/English with stable IDs and provenance. Not a season roster or live statistics feed.",
  },
  {
    id: "ihf",
    name: "IHF competition reports",
    category: "metadata",
    status: "candidate",
    url: "https://www.ihf.info/competitions",
    license: "Published reports; reuse terms require review",
    ar: "تقارير رسمية للمباريات واللاعبين والحراس بحسب البطولة. نراجع المستند وحق استخدامه قبل الاستيراد؛ لا يوجد موصل تلقائي حاليًا.",
    en: "Official match, player and goalkeeper reports by competition. Document format and reuse terms need review before import; no automatic connector yet.",
  },
  {
    id: "api-sports",
    name: "API-SPORTS Handball",
    category: "metadata",
    status: "candidate",
    url: "https://api-sports.io/sports/handball",
    license: "Provider terms; API key; free quota",
    ar: "خيار لنتائج ومواعيد كرة اليد. يجب التحقق من الموسم والبطولة في حساب تجريبي؛ الدوري المصري لم يُثبت في المراجعة. لا يوفّر تحليل الفيديو.",
    en: "Handball scores and fixtures candidate. Verify the competition/season using a trial account; Egyptian league coverage was not established. Not video analysis.",
  },
  {
    id: "thesportsdb",
    name: "TheSportsDB",
    category: "metadata",
    status: "research",
    url: "https://www.thesportsdb.com/docs_terms_of_use.php",
    license: "API terms; artwork rights are separate",
    ar: "بيانات مجتمعية قد تساعد في تعريف الفرق. التغطية متفاوتة، وبعض الإمكانات مدفوعة. نشر تطبيق في المتاجر يتطلب اشتراكًا وفق الشروط؛ الصور لا تُستورد تلقائيًا.",
    en: "Community metadata may help identify teams; coverage varies and some capabilities are paid. Store publication requires subscription under current terms; artwork is not imported automatically.",
  },
  {
    id: "bytetrack",
    name: "ByteTrack",
    category: "tracking",
    status: "research",
    url: "https://github.com/FoundationVision/ByteTrack",
    license: "MIT — code; weights/dependencies separate",
    ar: "أُضيفت تجربة مقارنة محلية باستخدام ByteTrack مع كاشف أقوى. تحتاج مراجعة ثبات الهوية والفقدان؛ لا تتعرف على أسماء اللاعبين أو التكتيك ولا تعمل تلقائيًا من واجهة التطبيق بعد.",
    en: "An optional local ByteTrack comparison with a stronger detector is available for identity/miss review. It does not identify athletes or tactics and is not invoked automatically by the web app.",
  },
  {
    id: "teamtrack",
    name: "TeamTrack",
    category: "tracking",
    status: "research",
    url: "https://github.com/AtomScott/TeamTrack",
    license: "MIT — repository code; dataset rights not established here",
    ar: "يتضمن كرة اليد وتصوير الملعب كاملًا ومعرّفات تتبّع. مفيد للتقييم؛ نتحقق من ترخيص حزمة البيانات قبل تنزيلها أو التدريب، ونختبر فرقها عن كاميرا البث.",
    en: "Includes handball, full-pitch footage and tracking IDs. Useful for evaluation; dataset package rights need verification before download/training, and broadcast domain differences need testing.",
  },
  {
    id: "eigd-h",
    name: "EIGD-H",
    category: "tracking",
    status: "research",
    url: "https://github.com/MM4SPA/eigd",
    license: "CC BY-NC-SA 4.0 — handball data",
    ar: "فيديو كرة يد مع مواقع وأحداث مرجعية، لكنه غير تجاري. مناسب لمسار بحث مستقل ضمن شروطه، وليس بيانات مضمّنة في المنتج.",
    en: "Handball video with synchronized positions and event labels, restricted to noncommercial use. Research option under its terms, not bundled product data.",
  },
  {
    id: "uniri",
    name: "UNIRI-HBD",
    category: "tracking",
    status: "research",
    url: "https://raass.uniri.hr/?p=653",
    license: "Verify exact IEEE DataPort version and terms",
    ar: "لقطات مصنفة لأفعال كرة اليد، مثل التمرير والتصويب والتقاطع. تفيد تجربة تصنيف الأفعال؛ ليست محركًا جاهزًا لفهم مباراة كاملة.",
    en: "Labeled handball actions such as passing, shooting and crossing. Action-classification research lead, not a ready full-match understanding engine.",
  },
  {
    id: "cvat",
    name: "CVAT Community",
    category: "annotation",
    status: "candidate",
    url: "https://github.com/cvat-ai/cvat",
    license: "MIT — community code; optional local tool",
    ar: "مراجعة وتصحيح صناديق ومسارات اللاعبين محليًا وتجهيز بيانات تقييم. يمكن تبادل ملفات MOT؛ لا نضيف خادمًا مطلوبًا إلى SESEN.",
    en: "Optional local review of boxes/tracks and evaluation annotation. MOT file interchange; no required new server in SESEN.",
  },
  {
    id: "trackeval",
    name: "TrackEval",
    category: "annotation",
    status: "candidate",
    url: "https://github.com/JonathonLuiten/TrackEval",
    license: "MIT — code; benchmark data separate",
    ar: "قياس جودة التتبّع بمقاييس مثل HOTA وIDF1 على بيانات يراجعها محلل. تصدير MOT أصبح متاحًا في الأداة المحلية؛ لا توجد نتيجة دقة معتمدة بعد.",
    en: "Tracking evaluation such as HOTA and IDF1 against reviewed labels. MOT export is available in the local tool; no validated accuracy result yet.",
  },
  {
    id: "handball-tracking",
    name: "Handball_Tracking",
    category: "tracking",
    status: "hold",
    url: "https://github.com/elymeraj/Handball_Tracking",
    license:
      "Repository grant unverified; YOLOv8 dependency and data require review",
    ar: "فكرة قريبة لهدفنا: كرة ولاعبون ومعايرة ملعب. لم نعتمد الكود أو الأوزان؛ ترخيص المستودع والتبعيات والبيانات يحتاج توضيحًا قبل الدمج.",
    en: "Relevant pipeline: ball, people and court calibration. Code/weights not adopted; repository permission, dependencies and dataset terms need clarification.",
  },
  {
    id: "sportslabkit",
    name: "SportsLabKit",
    category: "tracking",
    status: "hold",
    url: "https://github.com/AtomScott/SportsLabKit",
    license: "GPL-3.0 — current repository license",
    ar: "أدوات مفيدة للتتبّع والإحداثيات، لكن ليست تبعية MIT. نراجع التوافق قبل توزيع أي كود منها؛ ليست مثبتة في SESEN.",
    en: "Useful tracking/coordinate utilities, but not an MIT dependency. Review compatibility before distributing any code; not installed in SESEN.",
  },
  {
    id: "codehass",
    name: "handball-analytics-backend",
    category: "tracking",
    status: "hold",
    url: "https://github.com/codehass/handball-analytics-backend",
    license: "README declares MIT; standalone grant not verified",
    ar: "التصميم يعتمد FastAPI وAzure SQL/Blob وحوسبة Azure. لن نستبدل به تطبيقنا؛ لا يثبت وجود بيانات جاهزة للدوري المصري.",
    en: "Architecture uses FastAPI, Azure SQL/Blob and Azure compute. Not a replacement for our modular app, and not evidence of ready Egyptian league data.",
  },
  {
    id: "sportscore",
    name: "SportScore",
    category: "metadata",
    status: "hold",
    url: "https://sportscore.com/developers/",
    license: "Attribution-tier API; handball unsupported in reviewed docs",
    ar: "تصحيح للملف المرفق: التوثيق يذكر القدم والسلة والكريكيت والتنس. لا نعتمده مصدرًا لكرة اليد.",
    en: "Correction to the supplied PDF: documented sports are football, basketball, cricket and tennis. Not adopted as a handball feed.",
  },
  {
    id: "sportdb",
    name: "SportDB.dev",
    category: "metadata",
    status: "hold",
    url: "https://sportdb.dev/",
    license: "API key; 1,000 introductory requests; production pricing",
    ar: "1000 طلب بداية لا تعني خدمة مجانية بلا حدود؛ تغطية اليد المصرية لم تُثبت. لا نضعها اعتمادًا مطلوبًا.",
    en: "1,000 introductory requests do not establish unlimited free service; Egyptian handball coverage is unverified. Not a required dependency.",
  },
  {
    id: "belnaruto",
    name: "BelNaruto/handball-api",
    category: "metadata",
    status: "hold",
    url: "https://github.com/BelNaruto/handball-api",
    license: "Provider/subscription and code permission need verification",
    ar: "أمثلة التوثيق وحدها لا تثبت مصدر بيانات أو تغطية فعلية. نحتاج ردًا حقيقيًا وشروط استخدام واضحة قبل بناء موصل.",
    en: "Documentation examples do not establish a working data source or coverage. Needs real responses and clear terms before an adapter.",
  },
];
