const labels: Record<string, [string, string]> = {
  all: ["الكل", "All"],
  "result:goal": ["أهداف", "Goals"],
  "result:save": ["تصديات", "Saves"],
  "result:miss": ["إهدار", "Misses"],
  unknown: ["غير محدد", "Unknown"],
  other: ["غير مصنف", "Unclassified"],
  positional_attack: ["هجوم منظم", "Positional attack"],
  fast_break: ["هجوم سريع", "Fast break"],
  second_wave: ["موجة ثانية", "Second wave"],
  transition_defense: ["عودة دفاعية", "Defensive transition"],
  set_defense: ["دفاع منظم", "Set defense"],
  seven_vs_six: ["7 ضد 6", "7 vs 6"],
  empty_goal: ["مرمى خالٍ", "Empty goal"],
  power_play: ["تفوق عددي", "Power play"],
  short_handed: ["نقص عددي", "Short handed"],
  shot: ["تصويبة", "Shot"],
  goal: ["هدف", "Goal"],
  save: ["تصدٍ", "Save"],
  miss: ["إهدار", "Miss"],
  blocked: ["حجب", "Blocked"],
  assist: ["تمريرة حاسمة", "Assist"],
  turnover: ["فقد كرة", "Turnover"],
  steal: ["قطع كرة", "Steal"],
  block: ["حجب دفاعي", "Block"],
  duel: ["مواجهة فردية", "Duel"],
  seven_meter_won: ["حصول على 7م", "7m won"],
  two_minute_penalty: ["إيقاف دقيقتين", "2 minute suspension"],
  offensive_foul: ["خطأ هجومي", "Offensive foul"],
  defensive_foul: ["خطأ دفاعي", "Defensive foul"],
  timeout: ["وقت مستقطع", "Timeout"],
  lw: ["الجناح الأيسر", "Left wing"],
  rw: ["الجناح الأيمن", "Right wing"],
  left_half: ["نصف أيسر · تصنيف قديم", "Left half · legacy"],
  center: ["الوسط · تصنيف قديم", "Center · legacy"],
  right_half: ["نصف أيمن · تصنيف قديم", "Right half · legacy"],
  pivot_left: ["دائرة يسار", "Pivot left"],
  pivot_center: ["دائرة وسط", "Pivot center"],
  pivot_right: ["دائرة يمين", "Pivot right"],
  seven_meter: ["7 أمتار", "7 metres"],
  nine_meter_left: ["9م يسار", "9m left"],
  nine_meter_center: ["9م وسط", "9m center"],
  nine_meter_right: ["9م يمين", "9m right"],
  attacking_team: ["استحواذ المهاجم", "Attacking team"],
  defending_team: ["استحواذ المدافع", "Defending team"],
  out: ["خارج الملعب", "Out"],
  success: ["ناجح", "Success"],
  failure: ["غير ناجح", "Failure"],
  neutral: ["محايد", "Neutral"],
};
export function analysisLabel(code: string, lang: string) {
  return labels[code]?.[lang === "ar" ? 0 : 1] ?? code.replaceAll("_", " ");
}
